image: node:14.16.0

stages:
  - build
  - test
  - predeploy
  - deploy

cache: &global_cache # per-branch cache
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/
  # make push explicit
  policy: pull

build:
  stage: build
  script:
    - npm ci --cache .npm --prefer-offline
    # prepare script is skipped by install/ci when running NPM 6 as root.
    # This line can be safely removed with NPM 7+ (see NPM Changelog)
    - npm run prepare
    # Build demo application
    # Still some ESlint warnings to be fixed: disable ESlint at this stage
    - DISABLE_ESLINT_PLUGIN=true npm run build
  artifacts:
    paths:
      - node_modules/
      - dist/
      - build/
    expire_in: 3 days
  cache:
    <<: *global_cache
    policy: pull-push

deliver-internal:
  stage: deploy
  when: manual
  # use only artifacts from build job
  dependencies:
    - build
  before_script:
    - npm config set
      @concordant:registry "https://gitlab.inria.fr/api/v4/projects/${CI_PROJECT_ID}/packages/npm/"
    - npm config set
      '//gitlab.inria.fr/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken' "${CI_JOB_TOKEN}"
  script:
    - npm publish

# Expected environment variables (required to publish)
# - NPMJS_AUTH_TOKEN: NPMjs credentials
publish:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: manual
  # use only artifacts from build job
  dependencies:
    - build
  before_script:
    - npm config set
      '//registry.npmjs.org/:_authToken' "${NPMJS_AUTH_TOKEN}"
  script:
    - npm publish --access public

# Filter out node_modules from build artifacts to speed up deploy.
# Gitlab 13.10 will allow to use multiple cache instead.
pre-deploy:
  stage: predeploy
  rules:
    - if: "$CI_COMMIT_BRANCH"
  # use only artifacts from build job
  dependencies:
    - build
  # cache is not needed: don't download
  cache: {}
  # don't download repository content
  variables:
    GIT_STRATEGY: none
  artifacts:
    paths:
      - build/
  # script is required
  script:
    - echo Exporting build/…

deploy_review:
  stage: deploy
  rules:
    - if: "$CI_COMMIT_BRANCH"
      when: manual
      allow_failure: true
  tags:
    - webserver
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://demo.concordant.io/mdeditor_${CI_ENVIRONMENT_SLUG}/
    on_stop: stop_review
  # use only artifacts from pre-deploy job
  dependencies:
    - pre-deploy
  # cache and repository art not needed: don't download
  cache: {}
  variables:
    GIT_STRATEGY: none
  script:
    - rm -rf /var/www/demo.concordant.io/html/mdeditor_${CI_ENVIRONMENT_SLUG}
    - mv build /var/www/demo.concordant.io/html/mdeditor_${CI_ENVIRONMENT_SLUG}

stop_review:
  stage: deploy
  rules:
    - if: "$CI_COMMIT_BRANCH"
      when: manual
      allow_failure: true
  tags:
    - webserver
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  # artifacts, cache and repository are not needed: don't download
  dependencies: []
  cache: {}
  variables:
    GIT_STRATEGY: none
  script:
    - rm -rf /var/www/demo.concordant.io/html/mdeditor_${CI_ENVIRONMENT_SLUG}

deploy_live:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: manual
  tags:
    - webserver
  environment:
    name: live
    url: https://demo.concordant.io/mdeditor/
  # use only artifacts from pre-deploy job
  dependencies:
    - pre-deploy
  # cache and repository art not needed: don't download
  cache: {}
  variables:
    GIT_STRATEGY: none
  script:
    - rm -rf /var/www/demo.concordant.io/html/mdeditor
    - mv build /var/www/demo.concordant.io/html/mdeditor
